package tiendaUI;

import Excepciones.Excepcion_Definida;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tienda.dto.Producto;
import tienda.jdbc.CarroDaoJDBC;
import tienda.jdbc.TiendaDaoJDBC;
import utilities.IO;

/**
 *
 * @author finfanterodal
 */
public class ClienteTienda extends javax.swing.JFrame {

    //
    CarroDaoJDBC carro = new CarroDaoJDBC();
    TiendaDaoJDBC tienda = new TiendaDaoJDBC();

    /**
     * Creates new form Menu
     */
    public ClienteTienda() {
        initComponents();
        this.setTitle("Tienda.");
        this.setLocationRelativeTo(null);
        cargarTablaCatalogo();
        cargarTablaCarro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catalogoTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carroTable = new javax.swing.JTable();
        añadirB = new javax.swing.JButton();
        eliminarB = new javax.swing.JButton();
        quitarB = new javax.swing.JButton();
        confirmarB = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Catálogo:");

        catalogoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio/unidad (€)", "nº Unidades", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(catalogoTable);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Carro:");

        carroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio/unidad (€)", "nº Unidades", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(carroTable);

        añadirB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/añadirUnidades2.png"))); // NOI18N
        añadirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirBActionPerformed(evt);
            }
        });

        eliminarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminarProducto.png"))); // NOI18N
        eliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBActionPerformed(evt);
            }
        });

        quitarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quitarUnidades.png"))); // NOI18N
        quitarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarBActionPerformed(evt);
            }
        });

        confirmarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirmar.png"))); // NOI18N
        confirmarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quitarB, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(eliminarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(añadirB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(añadirB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quitarB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        eliminarB.getAccessibleContext().setAccessibleName("");
        eliminarB.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método añada una cantidad de producto dad por el usuario al carro
     * dadas las siguientes condiciones: 
     * 1. Si el producto ya existiese en el
     * carro no se podrían añadir unidades desde aquí. 
     * 2. Si el producto no existe y aparte son todas las unidades del producto que hay en el
     * catálogo, se inserta este en el carro y se borra del catálogo. 
     * 3.Si las unidades que se quieren añadir son menores de las que hay en el catálogo,
     * se inserta el producto en el carro y se modifica el producto en el
     * catálogo restándole dichas unidades.
     * 4. Si del producto del que se quieren añadir unidades no existe en el carro,
     * deberemos utilizar otr botón. 
     * 5. Si el producto existe y el número de
     * unidades es menor del que hay en la tienda(catálogo) nos actualiza el
     * producto del carro y también el de la tienda con el correspondiente nuevo
     * valor. 
     * 6. Si el producto existe y el número de unidades a añadir es igual
     * al de la tienda, elimina este último y actualiza el carro con el nuevo
     * valor.
     * 
     */
    private void añadirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBActionPerformed

        int fila = catalogoTable.getSelectedRow();
        int rows = 0;
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
        } else {
            try {
                int numUnidades = IO.introducirInt(IO.VENTANA, "Introduce la cantidad que deseas:");
                Producto product1 = new Producto(String.valueOf(catalogoTable.getValueAt(fila, 0)), Double.parseDouble(catalogoTable.getValueAt(fila, 1).toString()), Integer.parseInt(catalogoTable.getValueAt(fila, 2).toString()), String.valueOf(catalogoTable.getValueAt(fila, 3)));
                Producto productoaux = carro.buscarProducto(product1.getNome());

                if (productoaux == null) {
                    excepcionAñadirUnidades(product1, numUnidades);
                    if (numUnidades == product1.getNumUnid()) {
                        tienda.deleteProducto(product1.getNome());
                        rows = carro.insertProducto(product1, numUnidades);
                    } else if (numUnidades != product1.getNumUnid()) {
                        productoaux = product1;
                        productoaux.setNumUnid(productoaux.getNumUnid() - numUnidades);
                        tienda.updateProducto(productoaux);
                        rows = carro.insertProducto(product1, numUnidades);
                    }
                } else if (productoaux != null) {
                    excepcionAñadirUnidades(product1, numUnidades);
                    if (numUnidades == product1.getNumUnid()) {
                        productoaux.setNumUnid(productoaux.getNumUnid() + numUnidades);
                        tienda.deleteProducto(product1.getNome());
                        rows = carro.updateProducto(productoaux);
                    } else if (numUnidades != product1.getNumUnid()) {
                        productoaux.setNumUnid(productoaux.getNumUnid() + numUnidades);
                        product1.setNumUnid(product1.getNumUnid() - numUnidades);
                        tienda.updateProducto(product1);
                        rows = carro.updateProducto(productoaux);
                    }
                }

            } catch (Excepcion_Definida e) {
                IO.devolver(IO.VENTANA, e.getMessage());
            } catch (NumberFormatException e) {
                IO.devolver(IO.VENTANA, "No has introducido ningún valor");
            }
            IO.devolver(IO.VENTANA, "Registros insertados correctamente: " + rows);
            cargarTablaCatalogo();
            cargarTablaCarro();
        }

    }//GEN-LAST:event_añadirBActionPerformed
    
    
       /**
     * Este método elimina un producto seleccionado del carro cumpliendo las
     * siguientes condiciones: 1. Si del producto al que se desean eliminar
     * todabía quedan unidades en la tienda(catálogo), modifica este sumándole
     * las unidades del producto eliminado del caroo.
     * 2. Si el producto resulta
     * que ya no queda en la tienda, inserta directamente el producto que le
     * queremos eliminar del carro en la tienda.
     */
    private void eliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBActionPerformed

        int fila = carroTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
        } else {
            Producto product1 = new Producto(String.valueOf(carroTable.getValueAt(fila, 0)), Double.parseDouble(carroTable.getValueAt(fila, 1).toString()), Integer.parseInt(carroTable.getValueAt(fila, 2).toString()), String.valueOf(carroTable.getValueAt(fila, 3)));
            Producto productoaux = tienda.buscarProducto(product1.getNome());
            if (productoaux != null) {
                productoaux.setNumUnid(productoaux.getNumUnid() + product1.getNumUnid());
                tienda.updateProducto(productoaux);
            } else {
                productoaux = product1;
                tienda.insertProducto(productoaux);
            }
            int rows = carro.deleteProducto(product1.getNome());
            IO.devolver(IO.VENTANA, "Registros borrados correctamente: " + rows);
            cargarTablaCatalogo();
            cargarTablaCarro();
        }

    }//GEN-LAST:event_eliminarBActionPerformed

    private void confirmarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBActionPerformed
        this.setVisible(false);
        Confirmacion conf = new Confirmacion();
        conf.setVisible(true);
    }//GEN-LAST:event_confirmarBActionPerformed

    /**
     * Este método quita unidades del producto seleccionado del carro cumpliendo las siguientes condiciones:
     * 1. Si del producto al que se desean quitar unidades todabía quedan unidades en la tienda(catálogo), modifica este sumándole las unidades del producto del caroo.
     * 2. Si el producto resulta que ya no queda en la tienda, inserta directamente el producto al que le queremos quitae unidades del carro en la tienda, con el número de unidades especificado.
     * 3. Cuando el número de unidades a quitar es igual al que hay del producto en el carro lo elimina, y si es menor simplemente lo actualiza.
     */
    private void quitarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarBActionPerformed

        try {
            int numUnidades = IO.introducirInt(IO.VENTANA, "Introduce la cantidad que deseas quitar:");
            int fila = carroTable.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
            } else {
                Producto product1 = new Producto(String.valueOf(carroTable.getValueAt(fila, 0)), Double.parseDouble(carroTable.getValueAt(fila, 1).toString()), Integer.parseInt(carroTable.getValueAt(fila, 2).toString()), String.valueOf(carroTable.getValueAt(fila, 3)));
                Producto productoaux = tienda.buscarProducto(product1.getNome());
                int rows = 0;
                excepcionAñadirUnidades(product1, numUnidades);
                if (productoaux != null) {
                    productoaux.setNumUnid(productoaux.getNumUnid() + numUnidades);
                    tienda.updateProducto(productoaux);
                } else {
                    Producto product3 = new Producto(String.valueOf(carroTable.getValueAt(fila, 0)), Double.parseDouble(carroTable.getValueAt(fila, 1).toString()), Integer.parseInt(carroTable.getValueAt(fila, 2).toString()), String.valueOf(carroTable.getValueAt(fila, 3)));
                    product3.setNumUnid(numUnidades);
                    tienda.insertProducto(product3);
                }
                if (product1.getNumUnid() > numUnidades) {
                    product1.setNumUnid(product1.getNumUnid()-numUnidades);
                    rows = carro.updateProducto(product1);
                } else if(product1.getNumUnid() == numUnidades){
                    rows = carro.deleteProducto(product1.getNome());
                }

                IO.devolver(IO.VENTANA, "Registros borrados correctamente: " + rows);
            }
        } catch (Excepcion_Definida e) {
            IO.devolver(IO.VENTANA, e.getMessage());
        } catch (NumberFormatException e) {
            IO.devolver(IO.VENTANA, "No has introducido ningún valor");
        }
        cargarTablaCatalogo();
        cargarTablaCarro();


    }//GEN-LAST:event_quitarBActionPerformed


    /**
     * Recojo los datos del ArrayList actualizado y los añado a la tabla de la
     * interfaz.
     */
    public void cargarTablaCatalogo() {

        //Cargamos la tabla de la interfaz con los datos de la base que están almacenados en un Array
        DefaultTableModel model = (DefaultTableModel) catalogoTable.getModel();
        ArrayList<Producto> product = tienda.refreshArrayProductoTienda();
        model.setRowCount(0);
        for (int j = 0; j < product.size(); j++) {
            Object[] row = {product.get(j).getNome(), product.get(j).getPrecio(), product.get(j).getNumUnid(), product.get(j).getTipo()};
            model.addRow(row);
        }

    }

    /**
     * Recojo los datos del ArrayList actualizado y los añado a la tabla de la
     * interfaz.
     */
    public void cargarTablaCarro() {

        //Cargamos la tabla de la interfaz con los datos de la base que están almacenados en un Array
        DefaultTableModel mode2 = (DefaultTableModel) carroTable.getModel();
        ArrayList<Producto> product = carro.refreshArrayProductoCarro();
        mode2.setRowCount(0);
        for (int j = 0; j < product.size(); j++) {
            Object[] row = {product.get(j).getNome(), product.get(j).getPrecio(), product.get(j).getNumUnid(), product.get(j).getTipo()};
            mode2.addRow(row);
        }

    }

    //Trata que el número de unidades no pueda ser negativo y que elnúmero de unidades que queramos añadir al carro no pueda ser mayor de las unidades que hay en el catalogo.
    /**
     *
     * @param product
     * @param numUnid
     * @throws Excepcion_Definida
     */
    public void excepcionAñadirUnidades(Producto product, int numUnid) throws Excepcion_Definida {
        if (product.getNumUnid() < numUnid & numUnid > 0) {
            throw new Excepcion_Definida("Esa cantidad es mayor de la que hay en la tienda.");
        } else if (numUnid < 0) {
            throw new Excepcion_Definida("Esa cantidad no puede ser negativa.");
        }
    }

    //Trata que el número de unidades que queremos quitar no sea mayor del que hay y que este no sea un número negativo.
    /**
     *
     * @param product
     * @param numUnid
     * @throws Excepcion_Definida
     */
    public void excepcionQuitarUnidades(Producto product, int numUnid) throws Excepcion_Definida {
        if (product.getNumUnid() < numUnid) {
            throw new Excepcion_Definida("Esa cantidad es mayor de la que hay en el carro.");
        } else if (numUnid < 0) {
            throw new Excepcion_Definida("Esa cantidad no puede ser negativa.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirB;
    private javax.swing.JTable carroTable;
    private javax.swing.JTable catalogoTable;
    private javax.swing.JButton confirmarB;
    private javax.swing.JButton eliminarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton quitarB;
    // End of variables declaration//GEN-END:variables
}
